---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(magrittr)
```



```{r}
tibble::glimpse(mtcars)
```

```{r}
df_mtcars <- mtcars %>% 
  dplyr::mutate(across(c(cyl, vs, am, gear, carb), factor))
```

```{r}
tibble::glimpse(df_mtcars)
```

```{r}
m1 <- lm(mpg ~ cyl*wt, df_mtcars)
```

```{r}
tab_lm(m1,
       var_labels = c("cyl" = "Cylinders",
                      "wt" = "Weight",
                      "cyl * wt" = "Interaction"),
       caption = "Estimated Parameters for Fuel Efficiency Regressed on Automobile Aspects.",
       general_note = "Dependent variable is in miles per gallon (mph) and weight is in 1000's of pounds.  Data extracted from the 1974 Motor Trend US magazine.  n = 32.") 
```


```{r}
m2 <- lm(mpg ~ cyl + wt, df_mtcars)
```

```{r}
tab_lms(list(m2, m1),
        mod_names = c("Main Effects", "Moderation"),
        var_labels = c("cyl" = "Cylinders",
                       "wt" = "Weight",
                       "cyl * wt" = "Interaction"),
        fit = c("adj.r.squared", "AIC", "BIC", "logLik"),
        caption = "Estimated Parameters for Fuel Efficiency Regressed on Automobile Aspects.",
        general_note = "Dependent variable is in miles per gallon (mph) and weight is in 1000's of pounds.  Data extracted from the 1974 Motor Trend US magazine.  n = 32.") 
```

